export interface demographies{
    demographies:{
        title?:any;
    first_name?:any;
    last_name?:any;
    date_of_birth?:any;
    age?:any;
    gender?:any;
    race?:any;
    ethinicity?:any;
    language?:any;
    email?:any;
    home_address?:any;
    contact_number?:any;
    emergency_contact_details:{
        e_first_name?:any;
        e_last_name?:any;
      relationship?:any;
      email_address?:any;
      contact?:any;
      address?:any;
      patient_portal_access?:any;
      }
    
      },
      allergies:{
        allergyid?:any;
        allergyname?:any;
        type?:any;
        allergydescription?:any;
    }
  }